### ISSUE TITLE
Types of class methods are not shown

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty#290]
For example https://docs.lamin.ai/bionty.gene#bionty.Gene.add_source

This makes the docs much harder to read. It's not obvious for example that `source` can be a str or a Source record.

**Comment by falexwolf** [comment]
This is simply because it was forgotten to add the `Args:` section.

<img width="784" height="160" alt="Image" src="https://github.com/user-attachments/assets/d1ade00d-63dd-4cd1-9a66-1bb767a02137" />

**Comment by falexwolf** [comment]
Should also fix these annotations and docstrings on `Gene`:

<img width="386" height="380" alt="Image" src="https://github.com/user-attachments/assets/31d81b4a-bcb5-4a16-8288-53a0dc0a1f74" />

**Comment by Zethson** [comment]
Yeah, I'll have a look soon. Tons of Bionty documentation is terrible.

**Comment by falexwolf** [comment]
Also this should be fixed:

<img width="1531" height="99" alt="Image" src="https://github.com/user-attachments/assets/7641f787-7581-4e91-a2b2-a7c9aa58da22" />

We can of course just nitpick_ignore it if that's desired

**Comment by Zethson** [comment]
@namsaraeva FYI. This is because of the overloads. However, I guess we'll have to revert the overload as discussed.

**Comment by namsaraeva** [comment]
@Zethson let's revert. I'll make a PR for the Disease entity.

**Comment by Zethson** [comment]
@falexwolf I tried to fix the broken Organism/Record annotations that you showed above but didn't figure it out. Schema uses raw string `"lamindb.Schema"` annotations in the link models but using that for Record doesn't seem to fix it.

Do you have a guess?

**Comment by falexwolf** [comment]
I don't quite parse the problem. The quoted types should never be necessary given we have both from __future__ import annotations and TYPE_CHECKING

So, just regular types are used (almost?) everywhere?

**Comment by Zethson** [comment]
Correct. Record uses regular types which are not rendered and Schema uses strings which are rendered. Changing Record to strings doesn't fix it though.

<img width="772" height="760" alt="Image" src="https://github.com/user-attachments/assets/62a3f4a0-7fd1-46cf-abd6-be493b530140" />

is your screenshot.

 I am trying to figure out the difference between Record and Schema to learn why Record is not rendered, but Schema is. After spending some time I still have no clue. If you have a guess, I'd love to know about it, otherwise, I'll continue with more important things.
